from app.api import login
from app.api import email
from app.api import register_user
from app.api import verify_token
from app.api import movie_list
from app.api import movie_catgory
from app.api import movie_top
from app.api import movie_search
from app.api import address
from app.api import cinemas
from app.api import cinemas_movie
from app.api import movie_cinemas
from app.api import seat
from app.api import order
from app.api import send_code
from app.api import get_order
from app.api import pay_api
from app.api import admin_login
from app.api import pay_end
from app.api import query_talk
from app.api import send_talk
from app.api import admin_query
from app.api import drop_talk