from flask import Blueprint

#创建蓝图         蓝图名字，蓝图所在包
login = Blueprint('login', __name__)
email = Blueprint('email', __name__)
register_user = Blueprint('register_user', __name__)
verify_token = Blueprint('verify_token', __name__)
movie_list = Blueprint('movie_list', __name__)
movie_catgory = Blueprint('movie_catgory', __name__)
movie_top = Blueprint('movie_top', __name__)
movie_search = Blueprint('movie_search', __name__)
address = Blueprint('address', __name__)
cinemas = Blueprint('cinemas', __name__)
cinemas_movie = Blueprint('cinemas_movie', __name__)
movie_cinemas = Blueprint('movie_cinemas', __name__)
movie_seat = Blueprint('movie_seat', __name__)
movie_order = Blueprint('movie_order', __name__)
send_code = Blueprint('send_code', __name__)
get_order = Blueprint('get_order', __name__)
pay_api = Blueprint('pay_api', __name__)
admin_login = Blueprint('admin_login', __name__)
pay_end = Blueprint('pay_end', __name__)
save_user = Blueprint('save_user', __name__)
send_talk = Blueprint('send_talk', __name__)
query_talk = Blueprint('query_talk', __name__)
admin_query = Blueprint('admin_query', __name__)
drop_talk = Blueprint('drop_talk', __name__)